# Generated by Django 5.0.1 on 2024-03-18 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cita',
        ),
        migrations.AddField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.paciente'),
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
